---
jobs:
- name: notify-sandbox-users
  plan:
  - aggregate:
    - get: sandbox-config
    - get: notify-schedule
      trigger: true
  - task: notify
    file: sandbox-config/notify.yml
    params:
      API_ADDRESS: {{notify-api-url}}
      CLIENT_ID: {{notify-client-id}}
      CLIENT_SECRET: {{notify-client-secret}}
      ORG_NAME: {{notify-org-name}}
      SERVICE_NAMES: {{notify-service-names}}

- name: purge-sandboxes
  plan:
  - aggregate:
    - get: sandbox-config
    - get: purge-schedule
      trigger: true
  - task: purge
    file: sandbox-config/purge.yml
    params:
      API_ADDRESS: {{purge-api-url}}
      CLIENT_ID: {{purge-client-id}}
      CLIENT_SECRET: {{purge-client-secret}}
      ORG_NAME: {{purge-org-name}}

resources:
- name: sandbox-config
  type: git
  source:
    uri: {{sandbox-config-uri}}
    branch: {{sandbox-config-branch}}

- name: notify-schedule
  type: cron-resource
  source:
    expression: {{notify-schedule-expression}}
    location: {{notify-schedule-location}}

- name: purge-schedule
  type: cron-resource
  source:
    expression: {{purge-schedule-expression}}
    location: {{purge-schedule-location}}

resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-test
